name: beta-gov-app
recipe: drupal10
config:
  webroot: web

services:
  node:
    type: node:20
    globals:
      gulp-cli: latest
    build_as_root:  # Changed from build to build_as_root for global installs
      - npm install -g gulp-cli  # Explicitly install gulp-cli globally
    build:  # Regular build steps for your project
      - npm install
    command: npm start

tooling:
  npm:
    service: node
    cmd: npm
  node:
    service: node
    cmd: node
  gulp:
    service: node
    cmd: gulp
  watch-beta:
    service: node
    description: Runs GSA watch command from container
    dir: /app/web/themes/custom/gsa_beta
    cmd:
      - npx gulp watch
  watch-beta2:
    service: node
    description: Runs GSA watch command from container
    dir: /app/web/themes/custom/gsa_beta
    cmd:
      - npm gulp watch
