<?php

/**
 * @file
 * Gsa Beta theme.
 *
 * Place your custom PHP code in this file.
 */

/**
 * Implements hook_preprocess().
 */
function gsa_beta_subtheme_preprocess(&$variables) {
  // Set the path to the base theme.
  $variables['active_theme_path'] = base_path() . \Drupal::theme()->getActiveTheme()->getPath();
  $variables['uswds_images'] = $variables['active_theme_path'] . '/node_modules/@uswds/uswds/dist/img/';
}

function gsa_beta_preprocess_page(&$variables, $hook) {
  $variables['#attached']['library'][] = 'gsa_beta/global-styling';
}

function gsa_beta_preprocess(&$variables, $hook) {
  $variables['#attached']['library'][] = 'gsa_beta/global-styling';

  $theme_path = base_path() . \Drupal::service('extension.path.resolver')->getPath('theme', 'gsa_beta');
  $variables['theme_path'] = $theme_path;
}


/**
 * Implements hook_preprocess_field().
 */
function gsa_beta_preprocess_field(&$variables) {
  if ($variables['element']['#field_name'] === 'field_how_to_buy_form_this_contr') {
    $variables['attributes']['class'][] = 'your-custom-class2';
  }
}

/**
 * Implements hook_preprocess_paragraph().
 */
function gsa_beta_preprocess_paragraph(&$variables) {
  // Fetch the paragraph type
  $paragraph_type = $variables['paragraph']->getType();

  // Prepare to collect field information
  $variables['debug_fields_info'] = [];

  // Iterate over all fields in the paragraph
  foreach ($variables['paragraph'] as $field_name => $field) {
    if (strpos($field_name, 'field_') === 0) { // Check if it's a field
      $field_label = $variables['paragraph']->get($field_name)->getFieldDefinition()->getLabel();
      $field_value = $variables['paragraph']->get($field_name)->getValue();
      $variables['debug_fields_info'][$field_name] = [
        'label' => $field_label,
        'value' => json_encode($field_value) // Encode to JSON for easier readability
      ];
    }
  }

  // If you want to apply a custom class to a specific paragraph type
  if ($paragraph_type === 'the_paragraph_type') {
    $variables['custom_title_class'] = 'custom-class-for-title';
  }

  // Output the collected field data to your Twig template
  $variables['debug_info'] = json_encode($variables['debug_fields_info']);
}

