<?php

/**
 * @file
 * Gsa Beta theme.
 *
 * Place your custom PHP code in this file.
 */

/**
 * Implements hook_preprocess().
 */
function gsa_beta_subtheme_preprocess(&$variables) {
  // Set the path to the base theme.
  $variables['active_theme_path'] = base_path() . \Drupal::theme()->getActiveTheme()->getPath();
  $variables['uswds_images'] = $variables['active_theme_path'] . '/node_modules/@uswds/uswds/dist/img/';
}

function gsa_beta_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'gsa_beta/global-styling';
}
